<?php
/**
 * Created by PhpStorm.
 * User: thegingerdk
 * Date: 26/09/2017
 * Time: 13.19
 */

class Models extends DataBase {

	public function __construct($args = []) {

		foreach ( get_object_vars( $this ) as $key => $val ) {
			if(isset($args[$key])) $this->$key = $args[$key];
		}

		parent::__construct(); // TODO: Change the autogenerated stub
	}

	public function __get($name)
	{
		if(array_key_exists($name, get_object_vars($this))) {

			return $this->$name;
		}
		return null;
	}

	public function __set($name, $value)
	{
		if(array_key_exists($name, get_object_vars($this))) {

			$this->$name = $value;
		}
		return null;
	}

	public function toArray() {
		$vars = get_object_vars($this);
		unset($vars['hidden']);
		return $vars;
	}
}